// 工作区图标全部收敛到全应用共用图标集(apps/web/src/system/icons.tsx),
// 这里只做转发,保留既有 import 路径不动。
export {
  AlignIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CaretIcon,
  CheckIcon,
  CloseIcon,
  DiagonalArrowIcon,
  DeleteColumnIcon,
  ExternalLinkIcon,
  FullscreenIcon,
  FolderIcon,
  PlusIcon,
  MergeCellsIcon,
  QuoteIcon,
  RefreshIcon,
  SearchIcon,
  SettingsIcon,
  SparkleIcon,
  StatusDotIcon,
  StatusSquareIcon,
  SwapHorizontalIcon,
  WarningIcon,
} from "../../../system/icons";
export type { AlignVariant, CaretDirection } from "../../../system/icons";
