import type { PmMarkName, PmNodeName, PmThemeColor } from "./types";

export const PM_SCHEMA_NODE_NAMES = [
  "doc",
  "text",
  "hardBreak",
  "paragraph",
  "heading",
  "blockquote",
  "bulletList",
  "orderedList",
  "listItem",
  "horizontalRule",
  "codeBlock",
  "table",
  "tableRow",
  "tableCell",
  "tableHeader",
  "image",
  "diagram",
  "fileAttachment",
  "penNote",
  "taskList",
  "taskItem",
  "callout",
  "columnList",
  "column",
  "blockMath",
  "inlineMath",
] as const satisfies readonly PmNodeName[];

export const PM_SCHEMA_MARK_NAMES = [
  "bold",
  "italic",
  "underline",
  "strike",
  "code",
  "link",
  "textColor",
  "highlight",
] as const satisfies readonly PmMarkName[];

export const PM_HEADING_LEVELS = [1, 2, 3, 4, 5, 6] as const;
export const PM_DIAGRAM_LANGS = ["mermaid", "drawio"] as const;
// 高亮块主题槽:前 5 个为历史语义色,后 5 个为扩充的暖墨主题(赭石/绯霞/藕荷/黛青/青碧)。
// 仅作主题键用,样式在前端 .pm-callout--{tone} 承载;改这里会经 z.enum 自动传导到 validators/aiIrSchema。
export const PM_CALLOUT_TONES = [
  "info",
  "success",
  "warning",
  "danger",
  "neutral",
  "ochre",
  "rose",
  "mauve",
  "indigo",
  "teal",
] as const;
export const PM_TEXT_ALIGN_VALUES = ["left", "center", "right", "justify"] as const;
export const PM_IMAGE_ALIGN_VALUES = ["left", "center", "right"] as const;
export const PM_ORDERED_LIST_STYLES = [
  "decimal",
  "lower-alpha",
  "upper-alpha",
  "lower-roman",
  "upper-roman",
] as const;
export const PM_THEME_COLORS = [
  "ink",
  "gray",
  "slate",
  "brown",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "sage",
  "mint",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "magenta",
  "pink",
  "rose",
  "sand",
  "lavender",
] as const satisfies readonly PmThemeColor[];
export const PM_TEXT_COLORS = PM_THEME_COLORS;
export const PM_HIGHLIGHT_COLORS = PM_THEME_COLORS;
export const PM_THEME_TEXT_COLOR_VALUES: Record<PmThemeColor, string> = {
  ink: "#2f2a22",
  gray: "#5f625c",
  slate: "#44555c",
  brown: "#7a5234",
  red: "#a33a2a",
  orange: "#a65d1f",
  amber: "#927016",
  yellow: "#7f7418",
  lime: "#627a22",
  green: "#3f7a42",
  sage: "#57745c",
  mint: "#2f7b69",
  teal: "#24777a",
  cyan: "#27738e",
  sky: "#3f6e9a",
  blue: "#365d9f",
  indigo: "#4d55a0",
  violet: "#694c9a",
  purple: "#7a4d9b",
  magenta: "#974487",
  pink: "#a6476f",
  rose: "#a74755",
  sand: "#836d4a",
  lavender: "#6f5c8f",
};
export const PM_THEME_HIGHLIGHT_COLOR_VALUES: Record<PmThemeColor, string> = {
  ink: "#eee2c6",
  gray: "#e8e5dc",
  slate: "#dbe7e9",
  brown: "#ead8c7",
  red: "#f4d2ca",
  orange: "#f2d9bd",
  amber: "#f0e0ad",
  yellow: "#fff3a3",
  lime: "#e5efba",
  green: "#d4edd4",
  sage: "#dce9d7",
  mint: "#cfebe0",
  teal: "#cce8e7",
  cyan: "#cde8f0",
  sky: "#d7e7f6",
  blue: "#cfe0f5",
  indigo: "#d8dcf5",
  violet: "#e1d8f2",
  purple: "#e7d7ff",
  magenta: "#efd4ea",
  pink: "#f5d0cf",
  rose: "#f3d3d9",
  sand: "#eadfc8",
  lavender: "#e5ddf0",
};

export const pmSchemaSpec = {
  schemaVersion: 1,
  nodes: {
    doc: { content: "block+", attrs: ["schemaVersion"] },
    text: { group: "inline" },
    hardBreak: { group: "inline" },
    paragraph: { group: "block", content: "inline*", attrs: ["blockId", "textAlign"] },
    heading: { group: "block", content: "inline*", attrs: ["blockId", "level", "textAlign", "anchor"] },
    blockquote: { group: "block", content: "block+", attrs: ["blockId"] },
    bulletList: { group: "block", content: "listItem+", attrs: ["blockId"] },
    orderedList: { group: "block", content: "listItem+", attrs: ["blockId", "start", "listStyle"] },
    listItem: { group: "block", content: "paragraph block*", attrs: ["blockId"] },
    horizontalRule: { group: "block", attrs: ["blockId"] },
    codeBlock: { group: "block", content: "text*", attrs: ["blockId", "language"] },
    table: { group: "block", content: "tableRow+", attrs: ["blockId"] },
    tableRow: { content: "tableCell+" },
    tableCell: { content: "(paragraph|heading|blockquote|bulletList|orderedList|horizontalRule|codeBlock|image|diagram|fileAttachment|penNote|taskList|callout|columnList|blockMath)+", attrs: ["colspan", "rowspan", "colwidth", "backgroundColor"] },
    tableHeader: { content: "(paragraph|heading|blockquote|bulletList|orderedList|horizontalRule|codeBlock|image|diagram|fileAttachment|penNote|taskList|callout|columnList|blockMath)+", attrs: ["colspan", "rowspan", "colwidth", "backgroundColor"] },
    image: { group: "block", atom: true, attrs: ["blockId", "src", "alt", "title", "caption", "width", "height", "align"] },
    diagram: { group: "block", atom: true, attrs: ["blockId", "lang", "source", "svg", "height", "width", "align", "overlay"] },
    fileAttachment: { group: "block", atom: true, attrs: ["blockId", "fileId", "filename", "mimeType", "size"] },
    penNote: { group: "block", content: "inline*", attrs: ["blockId"] },
    taskList: { group: "block", content: "taskItem+", attrs: ["blockId"] },
    taskItem: { content: "paragraph block*", attrs: ["blockId", "checked"] },
    callout: { group: "block", content: "paragraph+", attrs: ["blockId", "emoji", "tone"] },
    // 内容分栏:columnList 是顶层块容器,内含 2+ 个 column;每个 column 容纳任意块。
    // widthRatio 为该列宽度占比(0~1,各列之和≈1);拖分隔线调宽窄。
    columnList: { group: "block", content: "column column+", attrs: ["blockId"] },
    column: { content: "block+", attrs: ["blockId", "widthRatio"] },
    blockMath: { group: "block", atom: true, attrs: ["blockId", "latex"] },
    inlineMath: { group: "inline", atom: true, attrs: ["latex"] },
  },
  marks: {
    bold: {},
    italic: {},
    underline: {},
    strike: {},
    code: {},
    link: { attrs: ["href", "title"] },
    textColor: { attrs: ["color"] },
    highlight: { attrs: ["color"] },
  },
} as const;
