// 根入口仅保留仓内实际消费的兼容 API；完整能力请从 package.json 声明的域 subpath 导入。
export {
  getQingagentSessionWorkspace,
  getQingagentSkills,
  qingagentAgent,
} from "./agents/qingagent.js";
export type {
  PendingConfirm,
  QingagentThreadMetadata,
  SessionState,
} from "./bridge/index.js";
export {
  AGENT_MAX_STEPS,
  QINGAGENT_RESOURCE_ID,
  TODO_AWARENESS_REQUEST_CONTEXT_KEY,
  UPLOADS_BASE,
  abortAndCleanupTurn,
  activeSuspensionOwnedBy,
  advanceLastContentEditedAt,
  appendAskUserAnswerMessageIfMissing,
  appendMissingVisibleAskUserAnswerMessagesFromChatHistory,
  buildAgentTracingMetadata,
  buildAskUserAnswerUserMessage,
  buildCapabilityTools,
  buildDocumentSnapshot,
  buildTodoAwarenessContent,
  buildVisibleAskUserAnswerMessage,
  beginTurnOwnership,
  bindTurnOwnershipToRequestContext,
  cleanRestoredText,
  clearStaleSuspensionIfInactive,
  clearSuspension,
  clonePmDoc,
  collectTopLevelTextBlocks,
  commitDocumentOp,
  commitPatches,
  commitReviewGroups,
  createSession,
  createSessionScopedTools,
  createSessionThread,
  deleteSessionThread,
  deriveActiveOverlay,
  deriveAgentBusy,
  deriveContentState,
  deriveDocStateFacts,
  deriveEditorState,
  deriveTitleFromSections,
  drainSessionPersistence,
  drainSessionPersistenceForSession,
  emitProjectedDocState,
  enrichAskUserResumeAnswersWithLabels,
  ensureDraftCandidateDoc,
  ensureWorkingMemorySnapshot,
  ensureWorkingMemorySnapshotWithStatus,
  endTurnOwnership,
  finalizeLingeringRunningToolCalls,
  failConfirmedToolCall,
  findLiteralMatches,
  findMaterialByFileId,
  getActiveSuspensionOwner,
  getDocumentVersionCommittedAt,
  hasActiveSuspension,
  hasVisibleAskUserAnswerMessage,
  invalidateDraftStateAfterCanonicalWrite,
  invalidateTurnOwnership,
  isSensitiveField,
  isDirectionReset,
  isOmSidecarEnabled,
  isPlanDraftTool,
  isQuestionnaireTool,
  listHomeSessionThreads,
  listSessionThreads,
  loadSessionFromThread,
  markSessionDeleted,
  resolveSessionDocumentId,
  unmarkSessionDeleted,
  migrateThreadMetadataToDocuments,
  normalizeAskUserAnswers,
  normalizeQuestionnaireSpecForRestore,
  normalizeRestoredDocStateKind,
  normalizeTargetDocState,
  persistSessionMetadata,
  prepareOmContextForTurn,
  processAgentStream,
  redactSensitiveText,
  replaceDraftCandidateDoc,
  replaceTextRuns,
  resolveFileIds,
  runAgentTurn,
  cancelConfirmedCommand,
  resumeConfirmDecision,
  scheduleOmSidecarAfterTurn,
  schedulePersist,
  serializeReviewOutcome,
  sessionIdToTraceId,
  settleDraftCandidate,
  stableErrorMaterialId,
  terminalizeAskUserToolCall,
  transitionDocState,
  updatePatchVerdict,
  upsertMaterialByFileId,
} from "./bridge/index.js";
export type { ApprovalAgent } from "./bridge/index.js";
export type { ConnectorInfoDto } from "./connectors/index.js";
export {
  CONFIRM_TTL_MS,
  ConfirmDecisionError,
  ConfirmService,
  clearAllApprovalProofs,
  clearApprovalProof,
  commandConfirmationDigest,
  confirmService,
  consumeApprovalProof,
  issueApprovalProof,
  secretLeaseStore,
} from "./confirm/index.js";
export type { SafeSubmitConfirmDecision } from "./confirm/index.js";
export {
  ConnectorService,
  createConnectorStatus,
  getConnectorService,
  isConnectorId,
  listConnectorDefinitions,
} from "./connectors/index.js";
export {
  PLATFORM_CREDENTIAL_SPECS,
  deleteCredential,
  listCredentialMeta,
  saveCredentialRecord,
} from "./credentials/index.js";
export { describeToolsForDebug } from "./debug/index.js";
export {
  DEFAULT_DIAG_ERROR_FIELD_BYTES,
  DEFAULT_DIAG_FIELD_BYTES,
  classifyDiagLayer,
  exportedSpanToDiagSpan,
  statusFromError,
  truncateField,
} from "./diagnostics/index.js";
export {
  browserFolderSourcesEnabled,
  cleanupOldFolderSourceCaches,
  clearFolderSourceCache,
  folderSourcesToWire,
  getSessionFolderSources,
  localFolderSourcesEnabled,
  markFolderSourceDetached,
  registerSessionFolderSources,
  unregisterSessionFolderSources,
} from "./folderSources/index.js";
export { pmToHomeArticleMeta } from "./home/index.js";
export type {
  DeepseekTier,
  ModelProvider,
  ModelOverrides,
  ModelParamOverrides,
  ModelProtocol,
} from "./llm/index.js";
export {
  DEEPSEEK_CONTEXT_WINDOWS,
  DEEPSEEK_MODEL_IDS,
  KIMI_BASE_URL,
  KIMI_MODEL_IDS,
  QINGAGENT_OM_OBSERVATIONS_REQUEST_CONTEXT_KEY,
  QINGAGENT_WORKING_MEMORY_REQUEST_CONTEXT_KEY,
  VISION_TEST_TIMEOUT_MS,
  beginSessionSnapshotTurn,
  clearSessionSnapshot,
  estimateCostCny,
  hasModelPricing,
  guardContext,
  guardReset,
  installNetProbe,
  modelFetch,
  resolveBaseUrl,
  resolveModelProvider,
  resolveModelParams,
  sanitizeBaseUrl,
  sanitizeModelId,
  testTextModelConnection,
  testVisionConnection,
  validateModelFetchUrl,
  warmUpModelEndpoint,
  withPrefixCacheGuardContext,
} from "./llm/index.js";
export {
  configureObservability,
  getMemory,
  getObservability,
  mastra,
} from "./mastra.js";
export type {
  SearchProviderConfig,
  SearchProviderConfigMap,
  SearchProviderErrorKind,
  SearchProviderId,
  SearchProviderRegistryEntry,
} from "./search/index.js";
export {
  SEARCH_PROVIDER_REGISTRY,
  SearchProviderError,
  clearManagedSearchProviderHealth,
  clearSearchCache,
  getSearchProviderHealth,
  invalidateManagedSearchConfig,
  invalidatePrimarySearchConfig,
  isSearchProviderId,
  markSearchProviderAuthFailed,
  markSearchProviderQuota,
  parsePrimarySearchConfig,
  parseSearchProviderConfig,
  recordSearchProviderError,
} from "./search/index.js";
export { seedInitialContent } from "./seed/seedInitialContent.js";
export {
  buildDraftTemplateSteeringTail,
  draftTemplate,
  parseDraftTemplate,
} from "./session/draftTemplate.js";
export {
  DerivativeDeltaBatcher,
  TRANSLATION_PUBLIC_FAILURE_REASON,
  buildTranslationSteeringTail,
  generateTranslationDerivative,
  generateTranslations,
} from "./session/translationGeneration.js";
export type { TranslationTarget } from "./session/translationGeneration.js";
export { clearQuestionBranch } from "./services/genService.js";
export {
  ARCHIVED_BUILTIN_SKILLS,
  BUILTIN_SKILLS_DIR,
  SKILLS_INSTALL_DIR,
  USER_SKILLS_DIR,
  checkCredentialPath,
  ensureCredentialPathExists,
  selectEffectiveCredentialPaths,
  isNeverAllowedCredentialPath,
  listCredentialRequests,
  pendingCredentialRequests,
  seedPresetCredentialGrants,
  listChildSkills,
  listTopLevelSkills,
  parseCredentialPathDeclarations,
  parseSkillFrontmatter,
  readDisabledSet,
  scanSkillHierarchy,
  setEnabled,
} from "./skills/index.js";
export type {
  CredentialPathDeclaration,
  CredentialRequest,
  DiscoveredSkill,
  ParsedSkillFrontmatter,
} from "./skills/index.js";
export {
  askUserTool,
  parseFileBuffer,
  readDocumentForSession,
  streamMoreQuestions,
} from "./tools/index.js";
export type { Material } from "./types/material.js";
export type {
  BrowserFolderBridgeBoundResponse,
  BrowserFolderBridgeEntry,
  BrowserFolderBridgeFailureReasonCode,
  BrowserFolderBridgeResponse,
  BrowserFolderBridgeStat,
} from "./workspace/index.js";
export {
  BROWSER_FOLDER_BRIDGE_FAILURE_REASON_CODES,
  SANDBOX_BIN_DIR,
  __resetBrowserFolderBridgeForTest,
  buildSandboxEnv,
  getBrowserFolderBridgeClientFolderIds,
  getBrowserFolderBridgePendingRequest,
  invalidateSessionWorkspace,
  isBrowserFolderBridgeClientRegistered,
  isBrowserFolderSourceRegistered,
  openBrowserFolderBridgeConnection,
  redactProbe,
  registerBrowserFolderSource,
  requestBrowserFolderBridge,
  resolveBrowserFolderBridgeResponse,
  resolveCredentialWallMode,
  resolveSandboxCredentialPaths,
  resolveIsolation,
  unregisterBrowserFolderSession,
  unregisterBrowserFolderSource,
} from "./workspace/index.js";
export {
  SETTING_DEEPSEEK_GLOBAL_KEY,
  SETTING_KIMI_GLOBAL_KEY,
  SETTING_MODEL_PROVIDER,
  SETTING_MODEL_PARAMS,
  SETTING_SEARCH_PRIMARY,
  SETTING_SEARCH_PROVIDER_CONFIG,
  __resetMigrationsForTest,
  aggregateUsageByDay,
  aggregateUsageBySession,
  aggregateUsageTotal,
  createDerivativeDoc,
  deleteDerivativeDoc,
  deleteAppSetting,
  deleteStyleTemplate,
  deleteReviewTemplate,
  documentDraftRepo,
  documentRepo,
  getDerivativeDocument,
  getDerivativeMeta,
  getReviewDocSupplement,
  getReviewTemplate,
  getSelectedReviewTemplate,
  getStyleTemplate,
  getAppSetting,
  getDocumentsClient,
  getVersionSnapshot,
  ignoreAnnotationGroups,
  insertReviewDismissalSignal,
  latestAgentUsageForSession,
  listDerivativesByThread,
  listLexiconEntries,
  listLexicons,
  listReviewTemplates,
  listStyleTemplates,
  listVersions,
  loadMainDocumentByThread,
  patchAppSettingJsonField,
  saveReviewTemplate,
  saveStyleTemplate,
  selectReviewTemplate,
  setAppSetting,
  setAppSettingJsonField,
  updateParams,
  upsertReviewDocSupplement,
} from "@qingagent/db";
export { validateFetchUrl } from "@qingagent/doc-render/browser";
