import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import { deleteStyleTemplate, getStyleTemplate, listStyleTemplates, saveStyleTemplate } from "@qingagent/db";
const slot=z.enum(["layout","writing","instruction"]);
const summary=z.object({id:z.string(),dtype:z.string(),slot,name:z.string(),detail:z.string(),builtin:z.boolean()});
export const styleTemplateListTool=createTool({id:"style_template_list",description:"列出排版或写作风格模板。",inputSchema:z.object({dtype:z.string().optional(),slot:slot.optional()}),outputSchema:z.object({ok:z.boolean(),templates:z.array(summary)}),execute:async i=>({ok:true,templates:(await listStyleTemplates(i)).map(({prompt:_,...x})=>x)})});
export const styleTemplateGetTool=createTool({id:"style_template_get",description:"读取一个风格模板的完整提示词。",inputSchema:z.object({id:z.string().min(1)}),outputSchema:z.object({ok:z.boolean(),template:summary.extend({prompt:z.string()}).optional(),error:z.string().optional()}),execute:async i=>{const template=await getStyleTemplate(i.id);return template?{ok:true,template}:{ok:false,error:"模板不存在"}}});
export const styleTemplateSaveTool=createTool({id:"style_template_save",description:"新建或更新排版、写作风格或常驻审查指令；更新内置模板后自动转为用户模板。",inputSchema:z.object({id:z.string().optional(),dtype:z.string().min(1),slot,name:z.string().min(1),detail:z.string().optional(),prompt:z.string()}),outputSchema:z.object({ok:z.boolean(),template:summary.extend({prompt:z.string()}).optional(),error:z.string().optional()}),execute:async i=>{try{return{ok:true,template:await saveStyleTemplate(i)}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e)}}}});
export const styleTemplateDeleteTool=createTool({id:"style_template_delete",description:"删除风格模板；同一 dtype 与 slot 每类至少保留一个。",inputSchema:z.object({id:z.string().min(1)}),outputSchema:z.object({ok:z.boolean(),deleted:z.boolean(),error:z.string().optional()}),execute:async i=>{try{const deleted=await deleteStyleTemplate(i.id);return{ok:deleted,deleted,error:deleted?undefined:"模板不存在"}}catch(e){return{ok:false,deleted:false,error:e instanceof Error?e.message:String(e)}}}});
