#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_PACKAGE="$ROOT_DIR/package.json"
DESKTOP_PACKAGE="$ROOT_DIR/apps/desktop/package.json"
LOCAL_STAMP_CONFIG="$ROOT_DIR/apps/desktop/build/release-extra-metadata.yml"

usage() {
  cat >&2 <<'USAGE'
Usage:
  ./scripts/release.sh bump <patch|minor|major>
  ./scripts/release.sh local-stamp
  ./scripts/release.sh verify-tag <tag>
USAGE
}

fail() {
  printf 'release.sh: %s\n' "$*" >&2
  exit 1
}

read_version() {
  node -e '
const fs = require("node:fs");
const [rootPath, desktopPath] = process.argv.slice(1);
const root = JSON.parse(fs.readFileSync(rootPath, "utf8"));
const desktop = JSON.parse(fs.readFileSync(desktopPath, "utf8"));
if (root.version !== desktop.version) {
  console.error(`version mismatch: root=${root.version}, desktop=${desktop.version}`);
  process.exit(1);
}
console.log(root.version);
' "$ROOT_PACKAGE" "$DESKTOP_PACKAGE"
}

ensure_release_semver() {
  local version="$1"
  if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    fail "package version must be plain SemVer x.y.z, got: $version"
  fi
}

ensure_clean_worktree() {
  if [[ -n "$(git -C "$ROOT_DIR" status --porcelain)" ]]; then
    fail "bump requires a clean worktree"
  fi
}

bump_version() {
  local kind="$1"
  case "$kind" in
    patch | minor | major) ;;
    *) fail "unknown bump kind: $kind" ;;
  esac

  ensure_clean_worktree

  local current
  current="$(read_version)"
  ensure_release_semver "$current"

  local next
  next="$(
    node -e '
const [version, kind] = process.argv.slice(1);
const parts = version.split(".").map((value) => Number.parseInt(value, 10));
if (parts.some((value) => !Number.isInteger(value) || value < 0)) {
  console.error(`invalid version: ${version}`);
  process.exit(1);
}
let [major, minor, patch] = parts;
if (kind === "major") {
  major += 1;
  minor = 0;
  patch = 0;
} else if (kind === "minor") {
  minor += 1;
  patch = 0;
} else if (kind === "patch") {
  patch += 1;
} else {
  console.error(`invalid bump kind: ${kind}`);
  process.exit(1);
}
console.log(`${major}.${minor}.${patch}`);
' "$current" "$kind"
  )"

  node - "$ROOT_PACKAGE" "$DESKTOP_PACKAGE" "$next" <<'NODE'
const fs = require("node:fs");
const [rootPath, desktopPath, next] = process.argv.slice(2);
for (const path of [rootPath, desktopPath]) {
  const packageJson = JSON.parse(fs.readFileSync(path, "utf8"));
  packageJson.version = next;
  fs.writeFileSync(path, `${JSON.stringify(packageJson, null, 2)}\n`);
}
NODE

  printf '%s\n' "$next"
  printf 'Updated package versions. Next: review diff, commit, push, and tag manually.\n' >&2
}

local_stamp() {
  local current
  current="$(read_version)"
  ensure_release_semver "$current"

  local sha
  sha="$(git -C "$ROOT_DIR" rev-parse --short HEAD)"

  local stamp
  stamp="${current}-dev.${sha}"

  mkdir -p "$(dirname "$LOCAL_STAMP_CONFIG")"
  cat >"$LOCAL_STAMP_CONFIG" <<EOF
# Generated by scripts/release.sh local-stamp. The build directory is gitignored.
# Use from apps/desktop with:
#   pnpm exec electron-builder --config build/release-extra-metadata.yml
extends: ../electron-builder.yml
extraMetadata:
  version: $stamp
EOF

  printf '%s\n' "$stamp"
}

verify_tag() {
  local tag="$1"
  if [[ ! "$tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-beta\.[0-9]+)?$ ]]; then
    fail "tag must look like v0.1.0 or v0.1.0-beta.1, got: $tag"
  fi

  local tag_version="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
  local current
  current="$(read_version)"

  if [[ "$tag_version" != "$current" ]]; then
    fail "tag version $tag_version does not match package.json version $current"
  fi

  printf 'tag %s matches package version %s\n' "$tag" "$current"
}

main() {
  local command="${1:-}"
  case "$command" in
    bump)
      [[ $# -eq 2 ]] || {
        usage
        exit 2
      }
      bump_version "$2"
      ;;
    local-stamp)
      [[ $# -eq 1 ]] || {
        usage
        exit 2
      }
      local_stamp
      ;;
    verify-tag)
      [[ $# -eq 2 ]] || {
        usage
        exit 2
      }
      verify_tag "$2"
      ;;
    *)
      usage
      exit 2
      ;;
  esac
}

main "$@"
